### ISSUE TITLE
能否统一分类，分割和检测一整套呢？

### ISSUE THREAD

**Issue by ChenCVer** [hhaAndroid/mmdetection-mini#1]

**Comment by ChenCVer** [comment]
还有，能否将SSD, RFBnet, faster rcnn， cascade rcnn这些优秀的检测算法集成进去？

**Comment by hhaAndroid** [comment]
统一所有任务，我觉得在mmdet里面做没有意义。因为这个框架设计时候就只考虑了目标检测，如果要强行兼容，是可以，但是代码就不优美了！如果想做大一统的框架，需要把mmdet继续抽象一层

至于检测优秀算法，我目前只会加入一阶段算法，二阶段的暂时不加了吧
