### ISSUE TITLE
程序挺好,就是运行不了,哭了...

### ISSUE THREAD

**Issue by huyunlei** [hhaAndroid/mmdetection-mini#11]

**Comment by huyunlei** [comment]
mmdection2.6的环境跑通了,您这个没跑通,

**Comment by hhaAndroid** [comment]
这个就比较尴尬了！mmdet2,6可以运行的原因是他把cuda提前帮你编译好了各种不同的版本，你可以下载直接用。但是我只有一台电脑无法帮你编译通过，比较麻烦！我的mini其实和他的是一样的，只是没有把cuda提前编译好而已，mmdet2以前版本也是需要自己编译的，现在改的更加友好而已！ 
我再想下有没有其他办法，可以免掉大家的cuda编译过程吧

**Comment by hhaAndroid** [comment]
我找到一个办法了：你把mmcv-full版本下载下来，然后解压，把里面的_ext.cpython-36m-x86_64-linux-gnu.so拷贝到mmdet/cv_core/路径下就可以不编译了。我刚才试了下没有问题！你可以试试

**Comment by huyunlei** [comment]
您好,我是windos环境,我现在已经把mmdetection2.0在windos跑通了,可是还是跑不通您这个,我的是cuda10.1,pytorch1.3,与这个有关系吗?

**Comment by huyunlei** [comment]
您上次说的那个方法,是不是linux平台,我看有个linux..

**Comment by huyunlei** [comment]
或者说,windos环境想跑您的程序,有什么建议吗

**Comment by Miki-lin** [comment]
> 我找到一个办法了：你把mmcv-full版本下载下来，然后解压，把里面的_ext.cpython-36m-x86_64-linux-gnu.so拷贝到mmdet/cv_core/路径下就可以不编译了。我刚才试了下没有问题！你可以试试

你好，你的代码很好，但是我也运行不了。我下载了你说的那个mmcv文件，然后解压，把_ext.cpython-37m-x86_64-linux-gnu.so这个文件放到cv_core那个文件夹下面，但是，我运行Python setup.py develop 还是报错
我的环境是：
Ubuntu18.04
cuda10.2
cudnn7.6.5
Python3.7.9
pytorch 1.6
torchvision 0.7
mmcv 1.1.5
mmcv-full 1.1.5
这是为什么，希望能答复！
我的环境可以运行mmdetection2.6.

**Comment by hhaAndroid** [comment]
你如果copy并且放置了so文件，那么Python setup.py develop是不需要运行的

**Comment by hhaAndroid** [comment]
已经替换了全新的安装方式，不再需要单独编译了！现在应该就好用多了
