### ISSUE TITLE
关于YOLOv4和YOLOv4-tiny的损失函数设置

### ISSUE THREAD

**Issue by gongchao99** [hhaAndroid/mmdetection-mini#12]
configs文件中关于YOLOv4和YOLOv4-tiny的损失函数设置不需要更改吗？没有看到使用了GIou loss啊

**Comment by hhaAndroid** [comment]
目前先不要进行训练哦，我目前仅仅是测试了转化和推理逻辑，训练逻辑还没有时间弄，后面等系列解读完成后才会开始弄
