### ISSUE TITLE
losses=self(**data)

### ISSUE THREAD

**Issue by zhangyuxin0** [hhaAndroid/mmdetection-mini#17]
你好，这一句我不是很明白训练过程中是如何计算损失呢，我看了代码到mmdet/models/detectors/base.py train_step()函数里面有这一句，能不能麻烦你讲解一下。

**Comment by ChenCVer** [comment]
我建议你可以多debug几次代码，一行一行分析，然后你就明白了，你这样问，谁都不好回答的



---Original---

**Comment by hhaAndroid** [comment]
losses = self(**data)这句话的意思是：调用类本身的forward方法，也就是：

if return_loss:
           return self.forward_train(img, img_metas, **kwargs)
else:
           return self.forward_test(img, img_metas, **kwargs)


对于训练来说，就是调用forward_train方法，如果子类实现了那就会调用子类的。

以retinanet为例，这句话实际上想调用的是mmdet/models/dense_heads/retina_head.py中的forward_train方法；但是由于该类没有实现，故会调用其父类mmdet/models/dense_heads/anchor_head.py的forward_train方法，但是该父类也没有实现，故会继续调用父类mmdet/models/dense_heads/base_dense_head.py的forward_train方法，也就是：

    def forward_train(self,
                      x,
                      img_metas,
                      gt_bboxes,
                      gt_labels=None,
                      gt_bboxes_ignore=None,
                      proposal_cfg=None,
                      **kwargs):
        outs = self(x) # forward方法被调用
        if gt_labels is None:
            loss_inputs = outs + (gt_bboxes, img_metas)
        else:
            loss_inputs = outs + (gt_bboxes, gt_labels, img_metas)
        losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore) #计算loss并返回
        # 核心操作，在训练过程中需要返回预测结果的，此时需要proposal_cfg不为none
        # 例如RPN head，其需要给rcnn进行refine
        if proposal_cfg is None:
            return losses
        else:
            # get_bboxes其实就是前向推理流程
            proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
            return losses, proposal_list

**Comment by hhaAndroid** [comment]
希望你能理解 @zhangyuxin0

**Comment by zhangyuxin0** [comment]
明白了，谢谢你的解答！
