### ISSUE TITLE
README笔记下的，第二章和第三章失效了

### ISSUE THREAD

**Issue by chenhaomingbob** [hhaAndroid/mmdetection-mini#2]
感谢大佬的工作。

**Comment by hhaAndroid** [comment]
好的，因为我还在修改，所以暂时取消了。明天就会开放

**Comment by ChenCVer** [comment]
回复这么快！



---原始邮件---
发件人: "深度眸"<notifications@github.com&gt;
发送时间: 2020年9月24日(周四) 中午1:33
收件人: "hhaAndroid/mmdetection-mini"<mmdetection-mini@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [hhaAndroid/mmdetection-mini] README笔记下的，第二章和第三章失效了 (#2)




 
好的，因为我还在修改，所以暂时取消了。明天就会开放
