### ISSUE TITLE
好奇mmdet的yolov3是出自本项目吗?怎么写法命名成员都一模一样

### ISSUE THREAD

**Issue by lfydegithub** [hhaAndroid/mmdetection-mini#21]
RT

**Comment by ChenCVer** [comment]
是的！你看看rryolov3，是不一样的



---原始邮件---
发件人: "pony"<notifications@github.com&gt;
发送时间: 2020年12月14日(周一) 下午2:05
收件人: "hhaAndroid/mmdetection-mini"<mmdetection-mini@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hhaAndroid/mmdetection-mini] 好奇mmdet的yolov3是出自本项目吗?怎么写法命名成员都一模一样 (#21)




 
RT

**Comment by lfydegithub** [comment]
> 是的！你看看rryolov3，是不一样的
> […](#)
> ---原始邮件--- 发件人: "pony"<notifications@github.com&gt; 发送时间: 2020年12月14日(周一) 下午2:05 收件人: "hhaAndroid/mmdetection-mini"<mmdetection-mini@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [hhaAndroid/mmdetection-mini] 好奇mmdet的yolov3是出自本项目吗?怎么写法命名成员都一模一样 (#21) RT — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

厉害了! good job
