### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by logic03** [hhaAndroid/mmdetection-mini#3]
请问您这个工程能在windows下运行吗？

**Comment by hhaAndroid** [comment]
可以，因为mmdetection中本身就支持。只是有几个操作不太支持windows，但是应该没有啥大影响。

**Comment by logic03** [comment]
> 可以，因为mmdetection中本身就支持。只是有几个操作不太支持windows，但是应该没有啥大影响。

这个yolov5是您自己实现的嘛？好厉害呀！基础性能指标和u版的一样嘛？

**Comment by hhaAndroid** [comment]
这个文章我还在写。目前yolov5只是完成了迁移而已，意思是还不支持训练。目前能做的事情是：可以直接导入yolov5训练好的权重，在mmdetection中进行预测，效果和yolov5里面完全相同。

我重写了yolov5的模型，bbox解码和图片前处理逻辑，和官方完全相同。现在就差训练部分了，其实就是差loss计算而已。

你现在要用或者想学习yolov5，你可以将yolov5模型转换到本框架中，然后就可以用了，mmdetection-mini里面提供了很多工具，你都可以用。

总之：yolov5模型可以直接在这里用，而且我把代码重构了，会更加容易理解！ 是学习yolov5的一个好方式！

后面会把loss部分加进来，就完整了。

**Comment by logic03** [comment]
> 这个文章我还在写。目前yolov5只是完成了迁移而已，意思是还不支持训练。目前能做的事情是：可以直接导入yolov5训练好的权重，在mmdetection中进行预测，效果和yolov5里面完全相同。
> 
> 我重写了yolov5的模型，bbox解码和图片前处理逻辑，和官方完全相同。现在就差训练部分了，其实就是差loss计算而已。
> 
> 你现在要用或者想学习yolov5，你可以将yolov5模型转换到本框架中，然后就可以用了，mmdetection-mini里面提供了很多工具，你都可以用。
> 
> 总之：yolov5模型可以直接在这里用，而且我把代码重构了，会更加容易理解！ 是学习yolov5的一个好方式！
> 
> 后面会把loss部分加进来，就完整了。

好的，谢谢您的耐心解答。
