### ISSUE TITLE
旋转目标检测

### ISSUE THREAD

**Issue by ming71** [hhaAndroid/mmdetection-mini#5]
是否有兴趣实现基于yolov5的旋转目标检测？可以在HRSC2016这种广泛采用的公开小型数据集上验证效果。

**Comment by hhaAndroid** [comment]
我可以参与你们项目，有问题可以问我

**Comment by ming71** [comment]
之前实现了旋转的yolov3效果一直不理想，准备有空把v4或者v5改成旋转检测，但是最近没什么时间想看看大佬如果准备实现的话想解一下性能如何。













在 2020-10-19 17:21:02，"深度眸" <notifications@github.com> 写道：

我可以参与你们项目，有问题可以问我

**Comment by hhaAndroid** [comment]
可以加我微信，先聊聊

**Comment by ming71** [comment]
18811028738



在 2020-10-19 21:19:03，"深度眸" <notifications@github.com> 写道：

可以加我微信，先聊聊

**Comment by 18804601171** [comment]
大佬，你好，请问你的DAL是怎么样的实现思路呢，可以开源一下代码吗
