### ISSUE TITLE
About YoloV4

### ISSUE THREAD

**Issue by www516717402** [hhaAndroid/mmdetection-mini#7]
Thank your for share this modify mmdet version.
Source YOLOV4 include many trick but dont find it in your project, such as Mosaic/AdversarialTraining etc.

**Comment by hhaAndroid** [comment]
Mosaic data enhancement already has pr in mmdet, but due to large changes, it has not been merged

**Comment by www516717402** [comment]
I also feel that adding mosaic will change a lot, so want to refer to implemented version.
