### ISSUE TITLE
train_cfg既然在FCOS中不需要，那为什么还要写呢？不能定义为空字典吗

### ISSUE THREAD

**Issue by lfydegithub** [hhaAndroid/mmdetection-mini#8]
https://github.com/hhaAndroid/mmdetection-mini/blob/4cc4ca868c183f2c4b709fad2607ba23448e3715/configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py#L44

**Comment by hhaAndroid** [comment]
可以直接设置为None,没关系的

**Comment by lfydegithub** [comment]
> 可以直接设置为None,没关系的

**Comment by lfydegithub** [comment]
> 可以直接设置为None,没关系的

我还纳闷呢 不是说是anchor-free嘛，怎么还有maxiou正负样本分配啊 QAQ，官网里的Config也有好几个anchor-free也是这样，有一些anchor-base的设置放在config文件里，但是却不使用，感觉有点迷惑小白
